subdir-ccflags-$(CONFIG_ARCH_MSM) += -Iarch/arm/mach-msm

obj-$(CONFIG_MACH_LENOVO_K920) += board-8974-k920.o
obj-$(CONFIG_MACH_LENOVO_K920) += board-8974-k920-gpiomux.o

obj-$(CONFIG_MACH_LENOVO_K920) += clock-krait-8974-k920.o clock-8974-k920.o

obj-$(CONFIG_MACH_LENOVO_K920) += lenovo_nv.o
obj-$(CONFIG_MACH_LENOVO_K920) += lenovo_hw.o
