ccflags-y += -Idrivers/media/platform/msm/camera_lenovo_v2
ccflags-y += -Idrivers/media/platform/msm/camera_lenovo_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_lenovo_v2/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
obj-$(CONFIG_MSMB_CAMERA) += onsemi_cmd.o
obj-$(CONFIG_MSMB_CAMERA) += onsemi_ois_init.o
